sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kd2/docker-react -f Dockerfile.dev .

# в лекции вместо -e стоит -- --coverage
script:
  - docker run -e CI=true kd2/docker-react npm run test
