version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: frontend
    ports:
    - 3000:3000
    volumes:
    - //frontend-src:/app/src
    - //frontend-public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true